# Generated by Django 5.2.1 on 2025-06-01 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_post_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
