# Generated by Django 5.2.1 on 2025-06-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='book_covers/standart_foto.png', null=True, upload_to='book_covers/'),
        ),
    ]
