# Generated by Django 5.2.1 on 2025-06-11 06:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_image'),
        ('recommendations', '0002_alter_recommendedbook_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedbook',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddIndex(
            model_name='recommendedbook',
            index=models.Index(fields=['user', '-score'], name='recommendat_user_id_39fa8c_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendedbook',
            index=models.Index(fields=['is_global', '-score'], name='recommendat_is_glob_b659fb_idx'),
        ),
    ]
